name: Code Metrics

on:
  push:
    branches:
      - main

jobs:
  analyze_code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Count Lines of Code
        run: git ls-files -z | xargs -0 wc -l
      - name: Save Line of Code Data
        run: echo "Lines of code:" > code_metrics.txt && git ls-files -z | xargs -0 wc -l >> code_metrics.txt && echo "\n" >> code_metrics.txt

      - name: Track Code Churn
        run: >
          echo -e "\nCode Churn:" >> code_metrics.txt &&
          git log -1 --numstat -M -C -- "*.gml" | 
          awk '{ added += $1; removed += $2 } END { print "Added:", added, "Removed:", removed }'
      - name: Save Code Churn Data
        run: >
          echo -e "\nCode Churn:" >> code_metrics.txt &&
          git log -1 --numstat -M -C -- "*.gml" | 
          awk '{ added += $1; removed += $2 } END { print "Added:", added, "Removed:", removed }' >> code_metrics.txt

      - name: Upload Metrics File
        uses: actions/upload-artifact@v4
        with:
          name: code-metrics
          path: code_metrics.txt
