name: Code Metrics

on:
  push:
    branches:
      - main

jobs:
  analyze_code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Count Lines of Code
        run: git ls-files | xargs wc -l

      - name: Track Code Churn
        run: >-
          git log --pretty=tformat: --numstat | 
          awk '{ added += $1; removed += $2 } END { print "Added:", added, "Removed:", removed }'
      - name: Save Code Churn Data
        run: >
          git log --pretty=tformat: --numstat | 
          awk '{ added += $1; removed += $2 } END { print "Added:", added, "Removed:", removed }' > code_metrics.txt

      - name: Upload Metrics File
        uses: actions/upload-artifact@v4
        with:
          name: code-metrics
          path: code_metrics.txt
